version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start-dev
    container_name: keycloak
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
